export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILED = 'ADD_EVENT_FAILED';

export const REMOVE_EVENT_REQUEST = 'REMOVE_EVENT_REQUEST';
export const REMOVE_EVENT_SUCCESS = 'REMOVE_EVENT_SUCCESS';
export const REMOVE_EVENT_FAILED = 'REMOVE_EVENT_FAILED';

export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUEST';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAILED = 'EDIT_EVENT_FAILED';

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED';

export const MONTHLY_DATES_REQUEST = 'MONTHLY_DATES_REQUEST';
export const MONTHLY_DATES_SUCCESS = 'MONTHLY_DATES_SUCCESS';
export const MONTHLY_DATES_FAILED = 'MONTHLY_DATES_FAILED';
